// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6dJZMitvzK7kxMTFLGvX7jVctdH-WsY',
    appId: '1:331727347991:web:30dc7bf7b47c890e3d5752',
    messagingSenderId: '331727347991',
    projectId: 'testauth-ff0b0',
    authDomain: 'testauth-ff0b0.firebaseapp.com',
    storageBucket: 'testauth-ff0b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0UE0SiZ4PkTAE57RWqF455oHrbHxalAI',
    appId: '1:331727347991:android:a447c9d3f13715d13d5752',
    messagingSenderId: '331727347991',
    projectId: 'testauth-ff0b0',
    storageBucket: 'testauth-ff0b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSrWMCELBrzHDpYRSh_1POs7_OaO0HkXA',
    appId: '1:331727347991:ios:dd5d50aeb3f759c43d5752',
    messagingSenderId: '331727347991',
    projectId: 'testauth-ff0b0',
    storageBucket: 'testauth-ff0b0.firebasestorage.app',
    iosBundleId: 'com.example.testAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSrWMCELBrzHDpYRSh_1POs7_OaO0HkXA',
    appId: '1:331727347991:ios:dd5d50aeb3f759c43d5752',
    messagingSenderId: '331727347991',
    projectId: 'testauth-ff0b0',
    storageBucket: 'testauth-ff0b0.firebasestorage.app',
    iosBundleId: 'com.example.testAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF6dJZMitvzK7kxMTFLGvX7jVctdH-WsY',
    appId: '1:331727347991:web:e0b2940183902ed43d5752',
    messagingSenderId: '331727347991',
    projectId: 'testauth-ff0b0',
    authDomain: 'testauth-ff0b0.firebaseapp.com',
    storageBucket: 'testauth-ff0b0.firebasestorage.app',
  );
}
